# Site
repository: Achab94/Achab94.github.io
# favicon: images/favicon.ico

# Personal info
name: Emanuele Degani
title: PhD student in Statistics, University of Padua
email: emanuele.degani@phd.unipd.it
website: https://achab94.github.io
telegram: https://t.me/achab94

# Social links
facebook_username: Achab94
twitter_username: Achab94
instagram_username: achab94
github_username:  Achab94
linkedin_username: emanuele-degani-b55a626a
#spotify_username: achab94

# About Section
# about_title: About Me
about_profile_image: images/foto.jpg
about_content: | # this will include new lines to allow paragraphs
  Hi, my name is Emanuele Degani and I am a PhD student in Statistics at the Department of Statistical Sciencens, University of Padua, Italy.

# Projects Section
# projects_title: Projects

# Experience Section
experience_title: Work Experience

# Education Section
# educaton_title: Education

# More Section
# more_title: Extras
# more_content: | # this will include new lines to allow paragraphs
#  Alongside my interests in networks and software engineering some of my other interests and hobbies are:
#   - Rock climbing
#   - Gaming
#   - Knitting
#   - [Becoming a ninja](https://www.youtube.com/watch?v=vtg4o__aRMg)

more_title: Award and grants
more_content: | #
   - Winner of the Mille e una lode a.a. 2016/2017, a tuition waiver University of Padua reserves to the 3% most brilliant students of each academic course.

# Footer
footer_show_references: false

# Build settings
remote_theme: sproogen/resume-theme

sass:
  sass_dir: _sass
  style: compressed

plugins:
 - jekyll-seo-tag
